@startuml frog-blossom-context
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(admin, "Admin")
System(cms, "frog-blossom-cms")

Rel(admin, user, "Create user", "https")
Rel(admin, cms, "Create content", "https")
Rel(admin, cms, "Update content", "https")
Rel(admin, cms, "Read content", "https")


Person(user, "User")
System(cms, "frog-blossom-cms")

Rel(user, cms, "Create content", "https")
Rel(user, cms, "Update content", "https")
Rel(user, cms, "Read content", "https")


@enduml