@startuml frog-blossom-context
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
System(cms, "frog-blossom-cms")

Rel(user, cms, "Create content", "https")
Rel(user, cms, "Update content", "https")
Rel(user, cms, "Read content", "https")


@enduml